# Generated by Django 5.2 on 2025-05-10 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_parent_groups_parent_is_staff_parent_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='api.parent')),
            ],
        ),
    ]
